### Register User
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "name": "Jaffar Dar",
    "email": "Jaffar@gmail.com",
    "password": "Jaffar@321",
    "role": "Doctor",
    "age": 38,
    "gender": "Male",
    "phone_number": "03211274567"
}

### Login User
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "password123"
}

###
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email": "doctor@example.com",
    "password": "password123"
}

### Get User Profile
GET http://localhost:5000/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTAzNTc2NTZmZGYyMmRjYWQ5NGRjYSIsImlhdCI6MTczMzMwOTgxNCwiZXhwIjoxNzM1OTAxODE0fQ.Gk1WAb7ziXFbhD-kBL6Y5LgzWO-mHfMplcX0mhGBg2w