### Register User
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "name": "Noor Fatima",
    "email": "noorfatimayousafzai@gmail.com",
    "password": "Noor@321",
    "role": "Patient",
    "age": 38,
    "gender": "Male",
    "phone_number": "03211274567"
}

### Register User
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "name": "Dr. Sarah Anjum",
    "email": "doctor@gmail.com",
    "password": "doctor123",
    "role": "Doctor",
    "age": 37,
    "gender": "Female",
    "phone_number": "03151574567"
}

###
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email": "doeh@example.com",
    "password": "password123"
}

### Login User
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email": "noorfatimayousafzai@gmail.com",
    "password": "Noor@321"
}

###
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email": "Smith@example.com",
    "password": "password123"
}

### Get User Profile
GET http://localhost:5000/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTAzNTc2NTZmZGYyMmRjYWQ5NGRjYSIsImlhdCI6MTczMzMwOTgxNCwiZXhwIjoxNzM1OTAxODE0fQ.Gk1WAb7ziXFbhD-kBL6Y5LgzWO-mHfMplcX0mhGBg2w