### Register User
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "name": "Noor Fatima",
    "email": "noorfatimayousafzai@gmail.com",
    "password": "Noor@321",
    "role": "Patient",
    "age": 38,
    "gender": "Male",
    "phone_number": "03211274567"
}

### Register User
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "name": "Dr. Shahzad",
    "email": "shahzad@gmail.com",
    "password": "shahzad123",
    "role": "Doctor",
    "age": 37,
    "gender": "Male",
    "phone_number": "03151574567"
}

###
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email": "doeh@example.com",
    "password": "password123"
}

### Login User
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email": "fatimarathore2018@gmail.com",
    "password": "password123"
}

###
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "password123"
}

### Get User Profile
GET http://localhost:5000/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTAzNTc2NTZmZGYyMmRjYWQ5NGRjYSIsImlhdCI6MTczMzMwOTgxNCwiZXhwIjoxNzM1OTAxODE0fQ.Gk1WAb7ziXFbhD-kBL6Y5LgzWO-mHfMplcX0mhGBg2w


### Get Notifications
GET http://localhost:5000/api/appointments/notifications/675434cefb2d19b713e97445
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTQzNGNlZmIyZDE5YjcxM2U5NzQ0NSIsImlhdCI6MTczMzU4NTE2MywiZXhwIjoxNzM2MTc3MTYzfQ.OuMZNwiUJWfGp7zbGdUskpUnSqrX5oOVwwoEYEsneNM

### Update User Profile
PUT http://localhost:5000/api/users/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTA0NDJlMTJlMzE1YmVhMzZkMmQ0YSIsImlhdCI6MTczMzU5NzE1NiwiZXhwIjoxNzM2MTg5MTU2fQ.zPY9Hthwbp28-dFT4fmhE5hp-SG5Nx5qpcPq5Yf1WW4

{
    "password": "thispassword123" 
}