GET http://localhost:5000/api/doctors
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTAzNjBhYjE2YTM2ZjZjZjg5Y2YwNiIsImlhdCI6MTczMzQxNTc4OCwiZXhwIjoxNzM2MDA3Nzg4fQ.FWzlVfCuxEUz5zXA8bUYc4IsqcVQHVU7gRSke-fg_I4
Content-Type: application/json

### Get Doctor by ID
GET http://localhost:5000/api/doctors/675039e1bb481a21276f3590
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTAzNmY0NmExNTc5NjUyNjk2ODI1MSIsImlhdCI6MTczMzMxMDE5NiwiZXhwIjoxNzM1OTAyMTk2fQ.mRrTUnf1hcD5bDo1z9gsLzdQLN1db1P3YKf59kh0V-8

### Create Doctor
POST http://localhost:5000/api/doctors
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTAzNjVhNmExNTc5NjUyNjk2ODI0OCIsImlhdCI6MTczMzMxMDA0MiwiZXhwIjoxNzM1OTAyMDQyfQ.vhJEMJDqLFsXdOmm0mVvfl43mxCvDTppfnphTWvt5Q0
Content-Type: application/json

{
    "user_id": "675433accaf1c6a1dd2cdc34",
    "specialization": "Child Specialist",
    "qualification": ["MBBS", "MD Pediatrics"],
    "description": "Dr. Sarah is a compassionate pediatrician who has dedicated her career to children's healthcare. She has extensive experience in treating various pediatric conditions and is known for her gentle approach.",
    "department_id": "67543352caf1c6a1dd2cdc2f",
    "shift": "Evening",
    "working_hours": "3PM-11PM",
    "availability_status": true,
    "experience": 10,
    "consultation_fee": 1000,
    "date_of_joining": "2022-03-15"
}

### Get Daily Schedule
GET http://localhost:5000/api/doctors/schedule/daily?doctor_id=675039e1bb481a21276f3590&date=2024-03-20
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTAzNzQ5NmExNTc5NjUyNjk2ODI1NyIsImlhdCI6MTczMzMxMDI4MSwiZXhwIjoxNzM1OTAyMjgxfQ.HdCrILiR1rieALWfs5C6fod3S11CFZ1D8D_H4ac6n3k

### Get Weekly Schedule
GET http://localhost:5000/api/doctors/schedule/weekly?doctor_id=675039e1bb481a21276f3590
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTAzNzQ5NmExNTc5NjUyNjk2ODI1NyIsImlhdCI6MTczMzMxMDI4MSwiZXhwIjoxNzM1OTAyMjgxfQ.HdCrILiR1rieALWfs5C6fod3S11CFZ1D8D_H4ac6n3k