### Create Medical Record
POST http://localhost:5000/api/medical-records
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTAzYTY4MDhmYmM3Y2NjYzIxMjFhNyIsImlhdCI6MTczMzU2OTQxNSwiZXhwIjoxNzM2MTYxNDE1fQ.jnjW03XHhx2IM6hH3Saje2oJOpZUW3XYZG_wrVcCkHk
Content-Type: application/json

{
    "patient_id": "6750af7e6dd96e12b38b5e93",
    "doctor_id": "6750afac6dd96e12b38b5ea1",
    "diagnosis": "Patient diagnosis here",
    "treatment": ["6750afc76dd96e12b38b5ea6"]
}

### Get Medical Record by ID
GET http://localhost:5000/api/medical-records/RECORD_ID_HERE
Authorization: Bearer YOUR_TOKEN_HERE

### Search Records by Patient
GET http://localhost:5000/api/medical-records/patient/6750af7e6dd96e12b38b5e93
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTAzYTY4MDhmYmM3Y2NjYzIxMjFhNyIsImlhdCI6MTczMzU2OTQxNSwiZXhwIjoxNzM2MTYxNDE1fQ.jnjW03XHhx2IM6hH3Saje2oJOpZUW3XYZG_wrVcCkHk