### Create Prescription
POST http://localhost:5000/api/prescriptions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTAzYTY4MDhmYmM3Y2NjYzIxMjFhNyIsImlhdCI6MTczMzU3NTI0NSwiZXhwIjoxNzM2MTY3MjQ1fQ.bQaCXCAkJt54LWirpP5qAyxl4sAAb3nxcnCLgrusWMs
Content-Type: application/json

{
    "patient_id": "6750af7e6dd96e12b38b5e93",
    "doctor_id": "6750afac6dd96e12b38b5ea1",
    "appointment_id": "675361c9d56e6dd893adb7e5",
    "medications": [
        {
            "name": "Medicine Name-------------",
            "dosage": "10mg",
            "frequency": "Twice daily",
            "duration": "7"
        }
    ],
    "instructions": "Take after meals"
}


### Get Prescription by ID
GET http://localhost:5000/api/prescriptions/patient/6750af7e6dd96e12b38b5e93
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTAzYjIxMDhmYmM3Y2NjYzIxMjFjYiIsImlhdCI6MTczMzU3NTMwOCwiZXhwIjoxNzM2MTY3MzA4fQ.9sDcvNCuDW0B8q9IjCzZnUs_SytkjoTxDBlWCakSEHQ